### ISSUE TITLE
compensation for personal suffering caused by measure 23

### ISSUE THREAD

**Issue by kniggos** [Enryah/muse-scores#1]
Ever since I listened to this and came across measure 23 I feel a tremendous tinnitus-like noise in my right ear. Hope this gets fixed in upcoming versions otherwise I might file a lawsuit to refund the costs of my daily visits to the otologist.

**Comment by Enryah** [comment]
If you pull the current version, you will notice that this issue has already been fixed. Next time, better use (ear) protection :)
